### ISSUE TITLE
Failed to connect to Blackmagic device at : dial tcp :9993: connect: connection refused When not configured

### ISSUE THREAD

**Issue by cpapplefamily** [Team254/cheesy-arena#206]
If not configured should this error not be log?

**Comment by patfair** [comment]
It shouldn't do anything if the address field from the settings page is blank:
```go
deviceAddresses := strings.Split(addresses, ",")
for i, address := range deviceAddresses {
	deviceAddresses[i] = strings.TrimSpace(address)
}
```
The above logic probably doesn't handle every non-blank-but-invalid edge case, though.

**Comment by cpapplefamily** [comment]
I been watching the CA logs as I been testing and noticed this output at the start and stop of every match. It doesn't seem to check that Blackmagic is being used. Maybe it doesn't cost anything to execute.
![image](https://github.com/user-attachments/assets/c3b4ea1a-2471-4c4a-af4c-40bcda90ae68)

**Comment by patfair** [comment]
I fixed the edge cases in the address parsing logic.

**Comment by cpapplefamily** [comment]
I'll pull them and watch.

You don't have the Github discussion tab for chats and I have a new
Comment/Question.
Looks like you added a print statement if the Arena.Run loop runs over
3000us.
 log.Printf("Warning: Arena loop iteration took a long time: %dus", time.
Since(loopStartTime).Microseconds())I

I started seeing this error at 3000 to 10000 too and was a bit
concerned until I realized it was microseconds and not milliseconds. In
your opinion what is acceptable and what is a concern? I was running with
NO filed equipment so everything from network configurations are finding
nothing.
Corey

**Comment by patfair** [comment]
I would only be concerned if I see that log line repeating consistently; on my machine I only see it maybe once or twice on startup and not again for tens of minutes. When you see it it's probably due to garbage collection or some other process spiking the CPU.

I added it when we were trying to diagnose the driver station protocol error over the summer, so that we can know if Cheesy Arena is ever at fault for not sending packets frequently enough.
